from django.db import models


NATIONALITY_CHOICES = (
    ('AFG', 'Afeganistão'),
    ('ALB', 'Albânia'),
    ('DEU', 'Alemanha'),
    ('AND', 'Andorra'),
    ('AGO', 'Angola'),
    ('ARG', 'Argentina'),
    ('ARM', 'Armênia'),
    ('AUS', 'Austrália'),
    ('AUT', 'Áustria'),
    ('AZE', 'Azerbaijão'),
    ('BHS', 'Bahamas'),
    ('BHR', 'Bahrein'),
    ('BGD', 'Bangladesh'),
    ('BRB', 'Barbados'),
    ('BEL', 'Bélgica'),
    ('BLZ', 'Belize'),
    ('BEN', 'Benim'),
    ('BLR', 'Bielorrússia'),
    ('BOL', 'Bolívia'),
    ('BIH', 'Bósnia e Herzegovina'),
    ('BWA', 'Botsuana'),
    ('BRA', 'Brasil'),
    ('BRN', 'Brunei'),
    ('BGR', 'Bulgária'),
    ('BFA', 'Burkina Faso'),
    ('BDI', 'Burundi'),
    ('BTN', 'Butão'),
    ('CPV', 'Cabo Verde'),
    ('CMR', 'Camarões'),
    ('KHM', 'Camboja'),
    ('CAN', 'Canadá'),
    ('QAT', 'Catar'),
    ('KAZ', 'Cazaquistão'),
    ('TCD', 'Chade'),
    ('CHL', 'Chile'),
    ('CHN', 'China'),
    ('CYP', 'Chipre'),
    ('COL', 'Colômbia'),
    ('COM', 'Comores'),
    ('COG', 'Congo'),
    ('PRK', 'Coreia do Norte'),
    ('KOR', 'Coreia do Sul'),
    ('CIV', 'Costa do Marfim'),
    ('CRI', 'Costa Rica'),
    ('HRV', 'Croácia'),
    ('CUB', 'Cuba'),
    ('DNK', 'Dinamarca'),
    ('DJI', 'Djibuti'),
    ('DMA', 'Dominica'),
    ('EGY', 'Egito'),
    ('SLV', 'El Salvador'),
    ('ARE', 'Emirados Árabes Unidos'),
    ('ECU', 'Equador'),
    ('ERI', 'Eritreia'),
    ('SVK', 'Eslováquia'),
    ('SVN', 'Eslovênia'),
    ('ESP', 'Espanha'),
    ('USA', 'Estados Unidos'),
    ('EST', 'Estônia'),
    ('ETH', 'Etiópia'),
    ('FJI', 'Fiji'),
    ('PHL', 'Filipinas'),
    ('FIN', 'Finlândia'),
    ('FRA', 'França'),
    ('GAB', 'Gabão'),
    ('GMB', 'Gâmbia'),
    ('GHA', 'Gana'),
    ('GEO', 'Geórgia'),
    ('GRD', 'Granada'),
    ('GRC', 'Grécia'),
    ('GTM', 'Guatemala'),
    ('GUY', 'Guiana'),
    ('GIN', 'Guiné'),
    ('GNB', 'Guiné-Bissau'),
    ('GNQ', 'Guiné Equatorial'),
    ('HTI', 'Haiti'),
    ('NLD', 'Holanda'),
    ('HND', 'Honduras'),
    ('HUN', 'Hungria'),
    ('YEM', 'Iêmen'),
    ('IND', 'Índia'),
)


class Actor(models.Model):
    name = models.CharField(max_length=60)
    birthday = models.DateField(null=True, blank=True)
    nacionality = models.CharField(
        max_length=60,
        choices=NATIONALITY_CHOICES,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.name
