# Generated by Django 5.2.1 on 2025-05-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nacionality', models.CharField(blank=True, choices=[('AFG', 'Afeganistão'), ('ALB', 'Albânia'), ('DEU', 'Alemanha'), ('AND', 'Andorra'), ('AGO', 'Angola'), ('ARG', 'Argentina'), ('ARM', 'Armênia'), ('AUS', 'Austrália'), ('AUT', 'Áustria'), ('AZE', 'Azerbaijão'), ('BHS', 'Bahamas'), ('BHR', 'Bahrein'), ('BGD', 'Bangladesh'), ('BRB', 'Barbados'), ('BEL', 'Bélgica'), ('BLZ', 'Belize'), ('BEN', 'Benim'), ('BLR', 'Bielorrússia'), ('BOL', 'Bolívia'), ('BIH', 'Bósnia e Herzegovina'), ('BWA', 'Botsuana'), ('BRA', 'Brasil'), ('BRN', 'Brunei'), ('BGR', 'Bulgária'), ('BFA', 'Burkina Faso'), ('BDI', 'Burundi'), ('BTN', 'Butão'), ('CPV', 'Cabo Verde'), ('CMR', 'Camarões'), ('KHM', 'Camboja'), ('CAN', 'Canadá'), ('QAT', 'Catar'), ('KAZ', 'Cazaquistão'), ('TCD', 'Chade'), ('CHL', 'Chile'), ('CHN', 'China'), ('CYP', 'Chipre'), ('COL', 'Colômbia'), ('COM', 'Comores'), ('COG', 'Congo'), ('PRK', 'Coreia do Norte'), ('KOR', 'Coreia do Sul'), ('CIV', 'Costa do Marfim'), ('CRI', 'Costa Rica'), ('HRV', 'Croácia'), ('CUB', 'Cuba'), ('DNK', 'Dinamarca'), ('DJI', 'Djibuti'), ('DMA', 'Dominica'), ('EGY', 'Egito'), ('SLV', 'El Salvador'), ('ARE', 'Emirados Árabes Unidos'), ('ECU', 'Equador'), ('ERI', 'Eritreia'), ('SVK', 'Eslováquia'), ('SVN', 'Eslovênia'), ('ESP', 'Espanha'), ('USA', 'Estados Unidos'), ('EST', 'Estônia'), ('ETH', 'Etiópia'), ('FJI', 'Fiji'), ('PHL', 'Filipinas'), ('FIN', 'Finlândia'), ('FRA', 'França'), ('GAB', 'Gabão'), ('GMB', 'Gâmbia'), ('GHA', 'Gana'), ('GEO', 'Geórgia'), ('GRD', 'Granada'), ('GRC', 'Grécia'), ('GTM', 'Guatemala'), ('GUY', 'Guiana'), ('GIN', 'Guiné'), ('GNB', 'Guiné-Bissau'), ('GNQ', 'Guiné Equatorial'), ('HTI', 'Haiti'), ('NLD', 'Holanda'), ('HND', 'Honduras'), ('HUN', 'Hungria'), ('YEM', 'Iêmen'), ('IND', 'Índia')], max_length=60, null=True)),
            ],
        ),
    ]
